apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: backend
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
