version: "3.5"
services:
    frontend:
        build: .
        ports:
            - "80:80"
        container_name: frontEnd
        restart: always
    backend:
        build: 
            context: backend
            dockerfile: Dockerfile
        ports:
            - "5002:5002"
        container_name: backEnd
